cluster-api-operator:
  core:
    cluster-api:
      namespace: "capi-operator-system"
      createNamespace: false
  bootstrap:
    kubeadm:
      namespace: "capi-operator-system"
      createNamespace: false
  controlPlane:
    kubeadm:
      namespace: "capi-operator-system"
      createNamespace: false
  ipam:
    in-cluster:
      namespace: "capi-operator-system"
      createNamespace: false
  infrastructure:
    proxmox:
      namespace: "capi-operator-system"
      createNamespace: false
    oci:
      namespace: "capi-operator-system"
      createNamespace: false
      version: v0.21.0
  manager:
    featureGates:
      proxmox:
        ClusterTopology: "true"
      oci:
        ClusterTopology: "true"
      core:
        ClusterTopology: "true"
      kubeadm:
        ClusterTopology: "true"
