core: 
  cluster-api:
    namespace: capi-operator-system
    createNamespace: false
    version: v1.9.11
bootstrap:
  kubeadm: 
    namespace: capi-operator-system
    createNamespace: false
    version: v1.9.11
controlPlane:
  kubeadm: 
    namespace: capi-operator-system
    createNamespace: false
    version: v1.9.11
ipam:
  in-cluster:
    namespace: capi-operator-system
    createNamespace: false
    verison: v0.1.0
infrastructure:
  proxmox:
    namespace: capi-operator-system
    createNamespace: false
    version: v0.7.4
manager:
  featureGates: 
    proxmox:
      ClusterTopology: "true"
    core: 
      ClusterTopology: "true"
    kubeadm:
      ClusterTopology: "true"
