core: "cluster-api"
bootstrap: "kubeadm"
controlPlane: "kubeadm"
ipam: "in-cluster"
infrastructure: "proxmox"
manager:
  featureGates: 
    proxmox:
      ClusterTopology: "true"
    core: 
      ClusterTopology: "true"
    kubeadm:
      ClusterTopology: "true"