apiVersion: v2
name: cluster-api-operator-wrapper
description: A Helm chart to wrap custom configs with cluster-api-operator
version: 0.1.0
dependencies: 
 - name: cluster-api-operator
   version: "0.23.0"
   repository: https://kubernetes-sigs.github.io/cluster-api-operator