#ipam:
#  operator:
#    clusterPoolIPV4PodCIDRList: 172.28.0.0/18
kubeProxyReplacement: true
envoyConfig:
  enabled: true
nodePort:
  enabled: true
ingressController:
  enabled: true
  loadbalancerMode: shared
l2announcements:
  enabled: true
externalIPs:
  enabled: true
