app: "cluster-api-operator"
chartRepoURL: "https://github.com/stenwt/argo-capi/charts/cluster-api-operator"
chartName: "cluster-api-operator-wrapper"
chartVersion: "0.1.0"
targetNamespace: "capi-operator-system"
